library(DT)
library(data.table)
library(arules)
library(arulesViz)
library(sqldf)
library(forecast)
library(shinydashboard)
library(shiny)
#library(shinythemes)
library(tidyr)
#library(tidyverse)
library(RSQLite)
library(dplyr)
library(plotly)
library(ggplot2)
require(reshape2)
require(Matrix)
require(grid)
options("scipen"=50, "digits"=4)

source("files.R", local = TRUE)
source("preprocess.R", local = TRUE)
source("server.R", local = TRUE)
source("ui.R", local = TRUE)

shinyApp(ui, server)
